---
- name: Deploy Docker container on Ubuntu Server
  hosts: all
  gather_facts: false
  become: yes
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: 
        - docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      tags: 
        - docker

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: subhodip703/calculator-backend
        source: pull
        state: present
      tags: 
        - docker

    - name: Run Docker container
      docker_container:
        name: calculator_backend_container
        image: subhodip703/calculator-backend
        state: started
        restart_policy: always
        published_ports:
          - "8083:8080"
      tags: 
        - docker
